spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scouterbase
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
security:
  ignored: /**
  enabled: false

keycloak:
  enabled: false