spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scouterbase
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop

keycloak:
  enabled: true
  auth-server-url: http://localhost:3002/auth
  realm: Scouterbase
  resource: scouterbase
  cors: on
  bearer-only: true
keycloak-admin:
    username: ScouterbaseAdmin
    password: ScouterbaseAdmin
