version: '3.5'

services:
  postgres-application:
    container_name: postgres-application
    image: postgres:alpine
    environment:
      POSTGRES_DB: scouterbase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped
  postgres-keycloak:
    container_name: postgres-keycloak
    hostname: postgres-keycloak
    image: postgres:alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.ch
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "3001:80"
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /import/scouterbase-realm.json
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_PASSWORD: password
    volumes:
    - ./keycloak:/import
    ports:
      - "3002:8080"
      - "443:8443"
    restart: unless-stopped
    depends_on:
      - postgres-keycloak
